### ISSUE TITLE
permission to access serial port

### ISSUE THREAD

**Issue by pepelillo** [ivmarkov/nx584#2]
This is the log.....

2022-09-22 21:36:20,049 controller ERROR Controller loop exited: [Errno 1] could not open port /dev/ttyUSB0: [Errno 1] Operation not permitted: '/dev/ttyUSB0'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/serial/serialposix.py", line 322, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
PermissionError: [Errno 1] Operation not permitted: '/dev/ttyUSB0'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/nx584/controller.py", line 851, in controller_loop_safe
    self.connect()
  File "/usr/lib/python3.10/site-packages/nx584/controller.py", line 396, in connect
    self._ser = SerialWrapper(self._portspec, self._config)
  File "/usr/lib/python3.10/site-packages/nx584/controller.py", line 288, in __init__
    self.connect()
  File "/usr/lib/python3.10/site-packages/nx584/controller.py", line 293, in connect
    connected = self._connect()
  File "/usr/lib/python3.10/site-packages/nx584/controller.py", line 362, in _connect
    self._s = serial.Serial(port, baudrate, timeout=0.25)
  File "/usr/lib/python3.10/site-packages/serial/serialutil.py", line 244, in __init__
    self.open()
  File "/usr/lib/python3.10/site-packages/serial/serialposix.py", line 325, in open

**Comment by ivmarkov** [comment]
I guess you have to google a bit how to allow permissions in hass to access the serial port...

**Comment by pepelillo** [comment]
Thanks for the suggestion.
I have HASSOS, supervised, and I have been using nx584 with the stock integration for 2 years. I start nx584_server inside the Homeassistant container without any permission issue. My only concern is about using the last version of pynx584 and the start method of the server (I use a shell command and the Homeasssitant boot event). 
Not sure if is a question of permissions i hass in general. but I try to google it  

Anyway can you kindly point me in the good direction?
Thanks

**Comment by ivmarkov** [comment]
> PermissionError: [Errno 1] Operation not permitted: '/dev/ttyUSB0

It is not how you start it, look at the log:
```
PermissionError: [Errno 1] Operation not permitted: '/dev/ttyUSB0
```

What it says is that it can't open the `/dev/ttyUSB0` device of the computer where you are running HASSOS *from within the docker container running this add-on*.

That's the issue. And what I'm saying is, you have to google how to configure the add-on container so that it can "see" and open the `/dev/tty/USB0` device on your host. Might require changes to the `Dockerfile`, but I haven't checked what changes exactly are necessary.

**Comment by juanjoSanz** [comment]
you need to add following option to addon config file:
`uart: true`
